basedir =  ../../..
resultsdir = ${basedir}/101results
tempsdir = ${basedir}/101temps
workerdir = ${basedir}/101worker
configsdir = ${workerdir}/configs
pulledLibrariesDir = ${resultsdir}/libraries
pulled101RepoDir = ${resultsdir}/101repo
pulled101DevDir = ${resultsdir}/101dev
webdir = ${basedir}/101web
web101RepoDir = ${basedir}/101web/101repo

wiki101FullCoreFilename = ${webdir}/dumps/Wiki101Full
wiki101SchemaERS = Wiki101Schema.ers
pulledLibrariesConfig = ${configsdir}/pulledLibraries.json