#!/bin/sh
set -e

bootstrapmsg () { echo "BOOTSTRAP: $1"; }

bootstrapmsg 'Installing git and make'
sudo apt-get install -y git make

bootstrapmsg 'Cloning 101worker'
git clone https://github.com/101companies/101worker.git

bootstrapmsg 'Installing 101worker dependencies'
cd 101worker
./install

bootstrapmsg 'Running 101worker unit tests'
./test
cd ..

bootstrapmsg 'Cloning 101test'
git clone https://github.com/101companies/101test.git

bootstrapmsg 'Installing 101test dependencies'
cd 101test
sudo make install

bootstrapmsg 'Running 101worker functional tests'
make all
cd ..

bootstrapmsg 'All done, 101worker is ready.'
