#!/bin/sh
set -e

bootstrapmsg () { echo "BOOTSTRAP: $1"; }

bootstrapmsg 'Installing git and make'
sudo apt-get install -y git make

git config --global user.name || {
    bootstrapmsg 'Setting your git user.name to "developer"'
    bootstrapmsg 'You might want to change this later'
    git config --global user.name developer
}

git config --global user.email || {
    bootstrapmsg 'Setting your git user.email to "101worker@example.com"'
    bootstrapmsg 'You might want to change this later'
    git config --global user.email 101worker@example.com
}

bootstrapmsg 'Cloning 101worker'
git clone https://github.com/101companies/101worker.git

bootstrapmsg 'Installing 101worker dependencies (needs sudo)'
cd 101worker
sudo ./install

bootstrapmsg 'Building 101worker pieces where necessary'
./install --build

bootstrapmsg 'Running 101worker unit tests'
./test
export worker101dir=`pwd`
cd ..

bootstrapmsg 'Cloning 101test'
git clone https://github.com/101companies/101test.git

bootstrapmsg 'Installing 101test dependencies'
cd 101test
sudo make install

bootstrapmsg 'Running 101worker functional tests'
make parallel
cd ..

bootstrapmsg 'All done, 101worker is ready.'
