run:
	@./App.py

debug:
	@echo running in debug mode - .debug.refinedTokens.json files will be produced
	@./App.py -debug

test:
	@echo not yet implemented

clean:
	@rm -f *.pyc

reset:
	@./App.py -reset
