#! /usr/bin/env python
# heavily inspired by https://github.com/srackham/w3c-validator/blob/master/w3c-validator.py

import os
import sys
import json
import commands

def validateCSS(fileName, x):
	cmd = 'java -jar ' + x + '/css-validator.jar --output=json file:' + fileName
	status, output = commands.getstatusoutput(cmd)
	output = output.replace('{vextwarning=false, output=json, lang=en, warning=2, medium=all, profile=css3}', '')
	w3cresult = json.loads(output)
	errors   = w3cresult['cssvalidation']['result']['errorcount']
	warnings = w3cresult['cssvalidation']['result']['warningcount']
	return (errors, warnings)



if len(sys.argv) < 2:
	sys.exit('Usage: css-validator filename [-silent] [-negative] [-validationapi]')

validatorPy = sys.argv[0]
x = os.path.dirname(validatorPy)

fileName = sys.argv[1]
verbose = True
negative = False

for arg in sys.argv:
	if arg == '-silent':
		verbose = False
	elif arg == '-negative':
		negative = True

if verbose:
	print 'checking ' + fileName

if fileName.endswith('.css'):
	(errorCount, warningCount) = validateCSS(fileName, x)
else:
	print "didn't recognize file - aborting..."
	sys.exit(1)	

if not negative:
	if errorCount:
		if verbose:
			print 'CSS validation failed with ' + str(errorCount) + ' error(s)'
		sys.exit(1)
	else:
		if verbose:
			print 'CSS validation succeeded'
		sys.exit(0)

if negative:
	if errorCount:
		if verbose:
			print 'CSS validation failed with ' + str(errorCount) + ' error(s) as expected'	
		sys.exit(0)
	else:
		if verbose:
			print "CSS validation succeeded, even though it shouldn't"
		sys.exit(1)
