#!/usr/bin/perl
use strict;
use warnings;
use File::Slurp   qw(write_file);
use LWP::Simple   qw(get);
use JSON          qw(encode_json decode_json);
use Repo101::Pull qw(pull101repo);

my %paths = map { ($_ => $ENV{$_} || die "Missing environment variable: $_") }
                qw(repo101 gitdeps101 repo101url gitdeps101url);

my $repos = do
{
    my $url     = $paths{gitdeps101url};
    my $content = get($url) or die "Couldn't fetch $url";
    decode_json($content)   or die "Couldn't decode JSON: $content"
};

my $changes = pull101repo(
    root_path => $paths{repo101   },
    deps_path => $paths{gitdeps101},
    root_url  => $paths{repo101url},
    repos     => $repos,
);

write_file('changes.json', JSON->new->utf8->pretty->encode($changes));
open my $fh, '>', 'changes' or die "Couldn't write to changes: $!";
print $fh "$changes->{$_} $_\n" for sort keys $changes;
