include ../Makefile.vars

build:
	cd ${pulled101RepoDir}/technologies/JFactExtractor; make build
	cd ${pulled101RepoDir}/technologies/JFragmentLocator; make build
	cd ${pulled101RepoDir}/technologies/HsFragmentLocator; make build
	cd ${pulled101RepoDir}/technologies/HsFactExtractor; make build
	cd ${pulled101RepoDir}/technologies/CSharpFragmentLocator; make build

 
	
