include ../Makefile.vars

build:
	cd ${pulled101RepoDir}/technologies/JFragmentLocator; make
	cd ${pulled101RepoDir}/technologies/CSharpFragmentLocator; make 
	cd ${pulled101RepoDir}/technologies/XmlFragmentLocator; make 
	
