include ../Makefile.vars

run: ${web101RepoDir} 
	php generateSourceDirectoryMatchingRules.php sourceDirectoryMatchingRules.csv ${sourceDirectoryMatchingRules}
	
${web101RepoDir}:
	mkdir ${web101RepoDir}

