SELECT DISTINCT ?contribution (COUNT(DISTINCT ?language) AS ?no_of_langs) (COUNT(DISTINCT ?technology) AS ?no_of_techs) (COUNT(DISTINCT ?concept) AS ?no_of_concepts) (COUNT(DISTINCT ?feature) AS ?no_of_features) WHERE {
  ?contribution rdf:type onto:Contribution .
  OPTIONAL {
     ?contribution onto:uses ?language .
     ?language rdf:type onto:Language .
  }
  OPTIONAL {
     ?contribution onto:uses ?technology .
     ?technology rdf:type onto:Technology .
  }
  OPTIONAL {
    ?contribution onto:implements ?feature .
    ?feature rdf:type onto:Feature .
  }
  OPTIONAL {
    ?concept rdf:type onto:Concept .  
    ?contribution ?p ?concept .
  }
}
GROUP BY ?contribution