SELECT ?paradigm ?concept (COUNT(DISTINCT ?contribution) AS ?count)
WHERE {
  ?language rdf:type onto:Language .
  ?contribution onto:uses ?language . 
  ?language rdf:type ?type_of_language . 
  ?type_of_language onto:supports ?paradigm . 

  ?concept rdf:type onto:Concept .
  ?contribution rdf:type onto:Contribution .
  ?contribution ?references ?concept .
}
GROUP BY ?paradigm ?concept
ORDER BY DESC(?count)
