SELECT ?concept ?headline (COUNT(?subject) AS ?count)
WHERE {
  ?concept a onto:Concept .
  ?concept onto:hasHeadline ?headline .
  ?subject ?predicate ?concept .
}
GROUP BY ?concept ?headline
ORDER BY DESC(?count)
