SELECT DISTINCT ?contributor ?paradigm WHERE {
 ?contributor rdf:type onto:Contributor .
 ?contribution rdf:type onto:Contribution .

 ?paradigm rdfs:subClassOf onto:Programming_paradigm .
 ?language rdf:type ?paradigm .

 ?contribution onto:uses ?language .
 ?contribution onto:developedBy ?contributor .
}