SELECT DISTINCT ?s WHERE {
 {
  ?s rdf:type onto:Language .
  ?s rdf:type onto:Technology .
 }
 UNION
 {
  ?s rdf:type onto:Concept .
  ?s rdf:type onto:Technology .
 }
 UNION
 {
  ?s rdf:type onto:Language .
  ?s rdf:type onto:Concept .
 }
 UNION
 {
  ?s rdf:type onto:Language .
  ?s rdf:type onto:Feature .
 }
 UNION
 {
  ?s rdf:type onto:Technology .
  ?s rdf:type onto:Feature .
 }
 UNION
 {
  ?s rdf:type onto:Concept .
  ?s rdf:type onto:Feature .
 }
}