SELECT DISTINCT ?language ?feature ?contribution (COUNT(DISTINCT ?all_features) AS ?no_of_features) WHERE {
 ?language rdf:type onto:Language .
 ?feature rdf:type onto:Feature .
 ?contribution rdf:type onto:Contribution .

 ?contribution onto:uses ?language .
 ?contribution onto:implements ?feature .
 ?contribution onto:implements ?all_features .
}
GROUP BY ?language ?feature ?contribution
ORDER BY DESC(?noOfFeatures)