SELECT ?language ?feature ?contribution (COUNT(DISTINCT ?lang_or_tech) AS ?sum_of_langs_and_techs) WHERE {
 ?contribution rdf:type onto:Contribution .
 ?language rdf:type onto:Language .
 ?feature rdf:type onto:Feature .

 ?contribution onto:uses ?language .
 ?contribution onto:implements ?feature .

 ?contribution onto:uses ?lang_or_tech .
 { ?lang_or_tech rdf:type onto:Language . }
   UNION
 { ?lang_or_tech rdf:type onto:Technology . }
}
GROUP BY ?language ?feature ?contribution
ORDER BY DESC(?sum_of_langs_and_techs)