### Search for script which introduce contributions where less complex ones are not yet introduced
### First the query gathers all scripts, their previous ones (dependsOn+) and the contributions the current script mentions (variable c). Then, the less complex contributions are gathered (variable contribution). 
### A second set is then created which is subtracted from the first set. In the second set, all contributions of previous lectures are gathered (in in addition to the contributions of the current script)   

SELECT DISTINCT ?script ?contribution WHERE {
   {
     ?script rdf:type onto:Script . 
     ?script onto:dependsOn+ ?previousLecture .
     ?previousLecture rdf:type onto:Script . 
  
     ?script onto:mentions ?c .
     ?c rdf:type onto:Contribution . 
     ?c onto:moreComplexThan* ?contribution . 
   } MINUS {
   	{
   		?previousLecture onto:mentions ?contribution . 
   		?contribution rdf:type onto:Contribution . 
   	} UNION {
   		?script onto:mentions ?contribution .
   	}
   }
}
