SELECT ?concept ?headline (COUNT(?subject) AS ?count)
WHERE {
  ?concept a onto:Concept .
  ?concept onto:hasHeadline ?headline .
  FILTER NOT EXISTS {
    ?classifier a onto:Classifier .
    ?classifier onto:classifies ?concept .
  } .
  ?subject ?predicate ?concept
}
GROUP BY ?concept ?headline
ORDER BY DESC(?count)
