SELECT ?property ?comment
WHERE {
  ?property rdfs:domain ?domain .
  ?property rdfs:range ?range .
  ?domain rdfs:subClassOf onto:Resource .
  ?property rdfs:comment ?comment 
}
ORDER BY ?property ?comment
