SELECT DISTINCT ?technology ?contribution (COUNT(DISTINCT ?feature) as ?number_of_features) ?more_complex_than WHERE {
 ?technology rdf:type onto:Technology .
 ?contribution rdf:type onto:Contribution .

 ?contribution onto:uses ?technology .
 ?contribution onto:implements ?feature .

 OPTIONAL { ?contribution onto:moreComplexThan ?more_complex_than . }
}
GROUP BY ?technology ?contribution ?more_complex_than 
ORDER BY DESC(?number_of_features)