#! /usr/bin/env python

import commands
import os.path
import sys

if len(sys.argv) > 3:
    sys.exit("Usage: validator.py inputFile")
locatorPy = sys.argv[0]
x = os.path.dirname(locatorPy)
command = "cd " + x + "; make"
status, output = commands.getstatusoutput(command)
if (status):
    print output
    sys.exit(status)
command = "mono " + x + "/bin/Debug/XMLValidator.exe " + sys.argv[1]
status, output = commands.getstatusoutput(command)

negativ = False
for arg in sys.argv:
	if arg == '-negativ':
		negativ = True
# good
if(status == 0) and not negativ:
	print output
	sys.exit(0)
elif negativ:
	print output + ' thus negativ testcase is valid'
	sys.exit(0)

print output
sys.exit(1)
