<?php

require_once 'main.config.local.php' ;  

//---------------------------------------------------------------
//        URL scheme of the 101 project 
//---------------------------------------------------------------

// project url
define('URL_PROJECT_101_URL','http://101companies.org') ;                                   

// wiki json representation
define('URL_WIKI_101_JSON_URL',ABSPATH_BASE.'101web/all.json') ;

//---------------------------------------------------------------
//         Local generated files
//---------------------------------------------------------------

// This directory is the place where various files are generated by the tools
// It serves as a temporary or testing space, some file being later deployed
// in the server.
define('ABSPATH_DATA_GENERATED',ABSPATH_BASE.'101web/') ;
