repo101dir      : $output/101repo/
gitdeps101dir   : $output/gitdeps/
repo101url      : https://github.com/101companies/101test
gitdeps101url   : file://$worker/configs/test/empty.json
config101       : $worker/configs/test/matches101meta.json
config101schema : $worker/schemas/config.schema.json
module101schema : $worker/schemas/module.schema.json

dumps101dir     : $output/101web/data/dumps/
targets101dir   : $output/101web/data/resources/
rules101dump    : $dumps101dir/rules.json
basics101dump   : $dumps101dir/matches.json
