#! /usr/bin/env python

import commands
import os.path
import sys

if len(sys.argv) != 2:
    sys.exit("Usage: validator.py inputFile")
    
command = "mono " + x + "/bin/Debug/XSDValidator.exe " + sys.argv[1]
status, output = commands.getstatusoutput(command)
print output
sys.exit(status)
