#!/usr/bin/perl
use strict;
use warnings;
use Graph;
use Test::More;
use Test::Differences;
use YAML qw(LoadFile);


sub gather_dependencies {
    my $dependee = shift;
    map { $_->[1] eq $dependee ? ($_->[0] => 1) : () } @_;
}


die 'Usage: validate_depend EXPECTED_GRAPH ACTUAL_GRAPH' if @ARGV != 2;
my $expected = LoadFile(shift);
my $actual   = LoadFile(shift);


my @everts = sort $expected->vertices;
my @averts = sort $actual  ->vertices;
is_deeply(\@everts, \@averts, 'same vertices');


my @eedges = sort $expected->edges;
my @aedges = sort $actual  ->edges;

my (%edeps, %adeps);
for my $module (@everts) {
    my $edeps = {gather_dependencies($module, @eedges)};
    my $adeps = {gather_dependencies($module, @aedges)};
    eq_or_diff($adeps, $edeps, "dependencies of $module");
}


done_testing;
