include ../Makefile.vars

run: 
	python -c 'from __init__ import *; main({ "type": "folders", "data": ["../../../101results/101repo"] })'

# Remove local temporary files, if any
clean:	
	@#no-op
