#! /usr/bin/env python


import os.path
import sys
import subprocess

locatorPy = sys.argv[0]
x = os.path.dirname(locatorPy)
command = "java -classpath " + x + ":"+ x + "/lib/* " + "jfactextractor.JFactExtractor "
subprocess.call([command], shell=True)
